home:
  max-homes: 3
  teleport-home:
    cooldown: 30  # cooldown in seconds
    cooldown-message: "&cYou are on cooldown. Please wait %seconds% seconds."
  messages:
    set-home: "&aYour home has been set."
    max-home: "&cYou have reached the max."
    teleport-home: "&bTeleporting to your home..."
    no-home: "&eYou haven't set a home with that name yet."
    delete-home: "&cYou have deleted home"

spawn:
  messages:
    teleport: "&bTeleporting to spawn..."
    cooldown: "&cYou are on cooldown. Please wait %seconds% seconds."
  cooldown: 30

tp:
  messages:
    teleport-to-player: "&bTeleported to %target%"
tpr:
  cooldown: 30
  expiretime: 30
messages:
  send: "&b tp request has been send to %target%"
  send-to: "&b you have a tp request from %player%"
  accept: "&b accepted request from %player%"
  acceptsender: "%player% has accepted your request"
  cooldown: "&cYou are on cooldown. Please wait %seconds% seconds."
  expire: "&b expired rquest from %player%"
  expiresender: "&b expired rquest send to %player%"
  error-norequestsend: "error %player% didn't send you a request"
  cancel: "&cYou cancelled the teleport request to %player%"
  cancelsender: "&c%player% cancelled the teleport request"