home:
  max-homes: 3
  messages:
    set-home: "&aYour home has been set."
    max-home: "&cYou have reached the max."
    teleport-home: "&bTeleporting to your home..."
    no-home: "&eYou haven't set a home with that name yet."
    delete-home: "&cYou have deleted home"

